// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var a = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var b = /* :: */[
  5,
  /* :: */[
    6,
    /* :: */[
      7,
      /* [] */0
    ]
  ]
];

var c = Pervasives.$at(a, b);

console.log($$Array.of_list(c));

exports.a = a;
exports.b = b;
exports.c = c;
/* c Not a pure module */
