// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function fn1(a, b) {
  return a - b | 0;
}

console.log(3);

console.log(-3);

var fn2 = 3;

var fn3 = -3;

exports.fn1 = fn1;
exports.fn2 = fn2;
exports.fn3 = fn3;
/*  Not a pure module */
