// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function addCoords(x, y) {
  return x + y;
}

console.log(Pervasives.string_of_float(2.0 + 3.0));

exports.addCoords = addCoords;
/*  Not a pure module */
