// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var m1 = /* record */[
  /* part1 */"hello",
  /* part2 */"world"
];

console.log(m1);

console.log("The End");

var part1 = "hello";

exports.m1 = m1;
exports.part1 = part1;
/*  Not a pure module */
