// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var i = /* Left */Block.__(0, [9]);

console.log(i);

console.log(9);

var myToDo = /* ToDo */Block.__(1, [
    "Write things",
    false
  ]);

var myNote = /* Note */Block.__(0, ["Remind me"]);

function show(anItem) {
  if (anItem.tag) {
    return "Todo: " + (anItem[0] + (", done?: " + Pervasives.string_of_bool(anItem[1])));
  } else {
    return "Note: " + anItem[0];
  }
}

console.log(show(myToDo));

console.log(show(myNote));

var ui = "Loading...";

console.log(ui);

var v = 9;

var state = /* Loading */0;

exports.i = i;
exports.v = v;
exports.myToDo = myToDo;
exports.myNote = myNote;
exports.show = show;
exports.state = state;
exports.ui = ui;
/*  Not a pure module */
